apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: read-eventhubs-write-kafka-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: read-eventhubs-write-kafka
        version: v1
    spec:
      containers:
        - name: read-eventhubs-write-kafka
          image: navicore/akka-eventhubs-kafka:latest
          imagePullPolicy: Always
          env:
          - name: EH_MODE
            value: "CONSUME"
          - name: TOPIC
            value: "CHANGE_ME"
          - name: BOOTSTRAP
            value: "CHANGE_ME"
          - name: EVENTHUBS_1_NAME
            value: "CHANGE_ME"
          - name: EVENTHUBS_1_NAMESPACE
            value: "CHANGE_ME"
          - name: EVENTHUBS_1_ENDPOINT
            value: "CHANGE_ME"
          - name: EVENTHUBS_1_CONSUMER_GROUP
            value: "CHANGE_ME"
          - name: EVENTHUBS_1_PARTITION_COUNT
            value: "CHANGE_ME"
          - name: EVENTHUBS_1_ACCESS_POLICY
            value: "CHANGE_ME"
          - name: EVENTHUBS_1_ACCESS_KEY
            value: "CHANGE_ME"
          - name: EVENTHUBS_1_CHECKPOINT_ACCOUNT
            value: "CHANGE_ME"
          - name: EVENTHUBS_1_CHECKPOINT_KEY
            value: "CHANGE_ME"
          - name: EVENTHUBS_1_CHECKPOINT_PATH
            value: "CHANGE_ME"
          ports:
          - containerPort: 8080

